# This workflow will install Python dependencies and run tests

name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, abmarl-epic-simplified-grid-world ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest
